export const Colors = {
  light: {
    text: "#11181C",
    background: "#fff",
    tint: "#0a7ea4",
    icon: "#687076",
    tabIconDefault: "#687076",
    tabIconSelected: "#0a7ea4",
  },
  dark: {
    text: "#ECEDEE",
    background: "#151718",
    tint: "#fff",
    icon: "#9BA1A6",
    tabIconDefault: "#9BA1A6",
    tabIconSelected: "#fff",
  }, // Add your app-specific colors
  app: {
    background: "#000",
    text: "#fff",
    textSecondary: "#666",
    textMuted: "#999",
    button: "#fff",
    buttonText: "#000",
    buttonDisabled: "#333",
    buttonTextDisabled: "#666",
    error: "#ff4444",
    errorBackground: "#2d1b1b",
    errorBorder: "#ff4444",
    errorText: "#ff6b6b",
    input: "#1a1a1a",
    inputBorder: "#333",
    card: "#1a1a1a",
  },
} as const;
